/**
 * Mock data matching contracts/api-contracts.ts types exactly.
 * All monetary values are in cents.
 * Used as fallback when API is not available in development.
 */

import type {
  DashboardSummary,
  BudgetSummary,
  GoalSummary,
  BillsSummary,
  Insight,
  AccountDetail,
  TransactionsSummary,
  Transaction,
  Account,
} from "@/contracts/api-contracts";

// ---------------------------------------------------------------------------
// Shared entities
// ---------------------------------------------------------------------------

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    date: "2026-04-23",
    time: "11:42 AM",
    merchant: "Trader Joe's",
    category: "Groceries",
    accountLabel: "Chase ··4521",
    amountInCents: 4820,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-2",
    date: "2026-04-23",
    time: "9:14 AM",
    merchant: "Spotify",
    category: "Subscriptions",
    accountLabel: "Chase ··4521",
    amountInCents: 1099,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-3",
    date: "2026-04-22",
    time: "5:30 PM",
    merchant: "Paycheck",
    category: "Income",
    accountLabel: "Ally Checking",
    amountInCents: 218000,
    type: "income",
    status: "posted",
  },
  {
    id: "tx-4",
    date: "2026-04-22",
    time: "2:18 PM",
    merchant: "Uber",
    category: "Transport",
    accountLabel: "Chase ··4521",
    amountInCents: 1450,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-5",
    date: "2026-04-22",
    time: "9:02 AM",
    merchant: "Coffee Bar",
    category: "Dining",
    accountLabel: "Chase ··4521",
    amountInCents: 640,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-6",
    date: "2026-04-21",
    time: "3:44 PM",
    merchant: "Amazon",
    category: "Shopping",
    accountLabel: "Chase ··4521",
    amountInCents: 3218,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-7",
    date: "2026-04-21",
    time: "11:08 AM",
    merchant: "Whole Foods",
    category: "Groceries",
    accountLabel: "Chase ··4521",
    amountInCents: 2875,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-8",
    date: "2026-04-20",
    time: "8:14 PM",
    merchant: "Venmo · Sam",
    category: "Transfers",
    accountLabel: "Ally Checking",
    amountInCents: 4500,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-9",
    date: "2026-04-20",
    time: "7:02 PM",
    merchant: "AMC Theaters",
    category: "Entertainment",
    accountLabel: "Chase ··4521",
    amountInCents: 2240,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-10",
    date: "2026-04-19",
    time: "6:45 PM",
    merchant: "Lyft",
    category: "Transport",
    accountLabel: "Chase ··4521",
    amountInCents: 920,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-11",
    date: "2026-04-19",
    time: "5:12 PM",
    merchant: "Trader Joe's",
    category: "Groceries",
    accountLabel: "Chase ··4521",
    amountInCents: 5230,
    type: "expense",
    status: "posted",
  },
  {
    id: "tx-12",
    date: "2026-04-18",
    time: "12:00 AM",
    merchant: "Interest",
    category: "Income",
    accountLabel: "Ally Savings",
    amountInCents: 412,
    type: "income",
    status: "posted",
  },
  {
    id: "tx-13",
    date: "2026-04-17",
    time: "9:00 AM",
    merchant: "Verizon",
    category: "Bills",
    accountLabel: "Chase ··4521",
    amountInCents: 6000,
    type: "expense",
    status: "posted",
  },
];

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: "chase",
    name: "Chase Checking",
    number: "··4521",
    balanceInCents: 324718,
    weekDeltaInCents: 21400,
    type: "checking",
    color: "var(--cat-6)",
    routingNumber: "021000021",
    linkedSince: "Feb 2025",
    lastSync: "2 min ago",
    balanceHistory: [
      280000, 300000, 260000, 320000, 280000, 340000, 300000, 360000, 320000,
      380000, 340000, 400000, 360000, 420000, 380000, 324718,
    ],
  },
  {
    id: "ally",
    name: "Ally Savings",
    number: "··8801",
    balanceInCents: 517340,
    weekDeltaInCents: 8000,
    type: "savings",
    color: "var(--cat-2)",
    apyBps: 425,
    routingNumber: "124003116",
    linkedSince: "Feb 2025",
    lastSync: "2 min ago",
    balanceHistory: [
      470000, 475000, 480000, 482000, 485000, 490000, 495000, 498000, 500000,
      502000, 505000, 508000, 510000, 512000, 515000, 517340,
    ],
  },
  {
    id: "broker",
    name: "Brokerage",
    number: "··2204",
    balanceInCents: 1421000,
    weekDeltaInCents: 24000,
    type: "investment",
    color: "var(--cat-4)",
    linkedSince: "Feb 2025",
    lastSync: "2 min ago",
    balanceHistory: [
      1300000, 1310000, 1290000, 1320000, 1295000, 1330000, 1305000, 1340000,
      1315000, 1350000, 1370000, 1360000, 1380000, 1395000, 1410000, 1421000,
    ],
  },
];

// ---------------------------------------------------------------------------
// Dashboard
// ---------------------------------------------------------------------------

export const MOCK_DASHBOARD: DashboardSummary = {
  user: { name: "Maya", initials: "MJ", lastSync: "2 min ago" },
  today: {
    date: "Tuesday, April 23",
    safeToSpendInCents: 7200,
    dailyAllowanceInCents: 9500,
    spentTodayInCents: 2300,
    percentSpentToday: 24,
  },
  cashOnHand: {
    totalInCents: 842000,
    weekDeltaInCents: 34000,
    cashFlowData: [
      1200, 1400, 1300, 1500, 1400, 1700, 1600, 1900, 1800, 2200, 2000, 2400,
      2200, 2600, 2500, 2800, 2700, 3000, 2900, 3200, 3100, 3300, 3200, 3500,
      3400, 3600, 3500, 3700, 3600, 3800,
    ],
    cashFlowDataByPeriod: {
      "1W": [760000, 772000, 768000, 785000, 791000, 810000, 842000],
      "1M": [
        700000, 710000, 705000, 720000, 715000, 730000, 725000, 745000,
        740000, 760000, 755000, 770000, 765000, 780000, 775000, 790000,
        785000, 800000, 795000, 810000, 805000, 815000, 810000, 822000,
        818000, 828000, 822000, 832000, 838000, 842000,
      ],
      "3M": [
        620000, 635000, 628000, 648000, 660000, 655000, 670000,
        665000, 682000, 695000, 690000, 710000, 842000,
      ],
      "1Y": [
        480000, 510000, 495000, 530000, 555000, 540000,
        580000, 610000, 595000, 640000, 710000, 842000,
      ],
    },
  },
  netWorth: {
    totalInCents: 2784300,
    monthDeltaInCents: 124000,
    totalAssetsInCents: 4263058,
    totalLiabilitiesInCents: 1478758,
  },
  actions: [
    {
      type: "bill",
      title: "Rent — $1,400",
      sub: "Due in 2 days · Auto-pay from Chase ✓",
      cta: "Review",
      tone: "accent",
      route: "/dashboard/bills",
    },
    {
      type: "insight",
      title: "82% of dining used",
      sub: "15 days left in the month",
      cta: "See spending",
      tone: "warn",
      route: "/dashboard/budgets",
    },
    {
      type: "todo",
      title: "3 to categorize",
      sub: "Amazon, Uber, Spotify",
      cta: "Categorize",
      tone: "primary",
      route: "/dashboard/transactions",
    },
  ],
  recentTransactions: MOCK_TRANSACTIONS.slice(0, 7),
  upcomingBills: [
    {
      id: "bill-1",
      name: "Rent",
      amountInCents: 140000,
      dueDate: "Apr 30",
      dueInDays: 2,
      isAutoPay: true,
      isUrgent: true,
      category: "Housing",
      icon: "home",
      color: "var(--cat-1)",
    },
    {
      id: "bill-2",
      name: "Internet",
      amountInCents: 6000,
      dueDate: "May 3",
      dueInDays: 10,
      isAutoPay: true,
      isUrgent: false,
      category: "Utilities",
      icon: "bill",
      color: "var(--cat-6)",
    },
    {
      id: "bill-3",
      name: "Credit card",
      amountInCents: 24500,
      dueDate: "May 8",
      dueInDays: 15,
      isAutoPay: false,
      isUrgent: false,
      category: "Card payment",
      icon: "card",
      color: "var(--cat-4)",
    },
    {
      id: "bill-4",
      name: "Gym",
      amountInCents: 2900,
      dueDate: "May 12",
      dueInDays: 19,
      isAutoPay: true,
      isUrgent: false,
      category: "Fitness",
      icon: "spark",
      color: "var(--cat-2)",
    },
  ],
  savingGoals: [
    {
      id: "goal-1",
      name: "Emergency fund",
      currentInCents: 340000,
      targetInCents: 500000,
      monthlyContributionInCents: 20000,
      percentageComplete: 68,
      eta: "Aug 2026",
      icon: "lock",
      color: "var(--cat-1)",
      vibe: "Safety net",
    },
    {
      id: "goal-2",
      name: "Trip to Lisbon",
      currentInCents: 62000,
      targetInCents: 200000,
      monthlyContributionInCents: 17500,
      percentageComplete: 31,
      eta: "Oct 2026",
      icon: "flag",
      color: "var(--cat-2)",
      vibe: "8-day adventure",
    },
    {
      id: "goal-3",
      name: "New laptop",
      currentInCents: 110000,
      targetInCents: 180000,
      monthlyContributionInCents: 25000,
      percentageComplete: 61,
      eta: "Jul 2026",
      icon: "card",
      color: "var(--cat-4)",
      vibe: "Work upgrade",
    },
  ],
  spendingCategories: [
    { name: "Rent & utilities", amountInCents: 52000, percentage: 42, color: "var(--cat-1)" },
    { name: "Groceries",        amountInCents: 28000, percentage: 22, color: "var(--cat-2)" },
    { name: "Dining",           amountInCents: 22000, percentage: 18, color: "var(--cat-3)" },
    { name: "Transport",        amountInCents: 14000, percentage: 11, color: "var(--cat-4)" },
    { name: "Other",            amountInCents:  8700, percentage:  7, color: "var(--cat-5)" },
  ],
  totalSpentThisMonthInCents: 124700,
};

// ---------------------------------------------------------------------------
// Budgets
// ---------------------------------------------------------------------------

export const MOCK_BUDGETS: BudgetSummary = {
  month: "April 2026",
  daysLeft: 7,
  totalSpentInCents: 83600,
  totalLimitInCents: 108000,
  percentageUsed: 77,
  remainingInCents: 24400,
  dailyLimitGoingForwardInCents: 3486,
  budgets: [
    { id: "b-1", name: "Groceries",     category: "Groceries",     limitInCents: 35000, spentInCents: 28000, percentageUsed: 80,  icon: "cart",   color: "var(--cat-2)", isOver: false },
    { id: "b-2", name: "Dining out",    category: "Dining",        limitInCents: 20000, spentInCents: 22000, percentageUsed: 110, icon: "coffee", color: "var(--cat-3)", isOver: true  },
    { id: "b-3", name: "Transport",     category: "Transport",     limitInCents: 18000, spentInCents: 14000, percentageUsed: 78,  icon: "car",    color: "var(--cat-4)", isOver: false },
    { id: "b-4", name: "Shopping",      category: "Shopping",      limitInCents: 20000, spentInCents:  8700, percentageUsed: 44,  icon: "bag",    color: "var(--cat-5)", isOver: false },
    { id: "b-5", name: "Entertainment", category: "Entertainment", limitInCents: 10000, spentInCents:  6500, percentageUsed: 65,  icon: "play",   color: "var(--cat-6)", isOver: false },
    { id: "b-6", name: "Subscriptions", category: "Subscriptions", limitInCents:  5000, spentInCents:  4400, percentageUsed: 88,  icon: "music",  color: "var(--cat-1)", isOver: false },
  ],
  dailySpendHistory: Array.from({ length: 30 }, (_, i) => ((i * 37 + 13) % 100) * 500),
  vsLastMonth: [
    { category: "Groceries",  deltaInCents: -2000, tone: "pos" },
    { category: "Dining",     deltaInCents:  4500, tone: "neg" },
    { category: "Transport",  deltaInCents: -1000, tone: "pos" },
    { category: "Shopping",   deltaInCents: -3800, tone: "pos" },
  ],
};

// ---------------------------------------------------------------------------
// Goals
// ---------------------------------------------------------------------------

export const MOCK_GOALS: GoalSummary = {
  totalSavedInCents: 531200,
  totalTargetInCents: 980000,
  totalMonthlyContributionInCents: 77500,
  savingsRatePercent: 23,
  savingsRateDeltaPoints: 5,
  activeTransfers: 4,
  goals: [
    {
      id: "goal-1",
      name: "Emergency fund",
      currentInCents: 340000,
      targetInCents: 500000,
      monthlyContributionInCents: 20000,
      percentageComplete: 68,
      eta: "Aug 2026",
      icon: "lock",
      color: "var(--cat-1)",
      vibe: "Safety net",
    },
    {
      id: "goal-2",
      name: "Trip to Lisbon",
      currentInCents: 62000,
      targetInCents: 200000,
      monthlyContributionInCents: 17500,
      percentageComplete: 31,
      eta: "Oct 2026",
      icon: "flag",
      color: "var(--cat-2)",
      vibe: "8-day adventure",
    },
    {
      id: "goal-3",
      name: "New laptop",
      currentInCents: 110000,
      targetInCents: 180000,
      monthlyContributionInCents: 25000,
      percentageComplete: 61,
      eta: "Jul 2026",
      icon: "card",
      color: "var(--cat-4)",
      vibe: "Work upgrade",
    },
    {
      id: "goal-4",
      name: "Wedding gift",
      currentInCents: 20000,
      targetInCents: 50000,
      monthlyContributionInCents: 15000,
      percentageComplete: 40,
      eta: "Jun 2026",
      icon: "heart",
      color: "var(--cat-3)",
      vibe: "Sara & Tom",
    },
  ],
};

// ---------------------------------------------------------------------------
// Bills
// ---------------------------------------------------------------------------

export const MOCK_BILLS: BillsSummary = {
  periodDays: 30,
  totalDuePeriodInCents: 189300,
  totalSubsMonthlyInCents: 4897,
  totalSubsAnnualInCents: 58764,
  savingsOpportunityInCents: 1799,
  savingsOpportunityNote:
    "Cancel Figma and iCloud — you haven't used them in 30+ days",
  bills: [
    {
      id: "bill-1",
      name: "Rent",
      amountInCents: 140000,
      dueDate: "Apr 30",
      dueInDays: 2,
      isAutoPay: true,
      isUrgent: true,
      category: "Housing",
      icon: "home",
      color: "var(--cat-1)",
    },
    {
      id: "bill-2",
      name: "Internet · Verizon",
      amountInCents: 6000,
      dueDate: "May 3",
      dueInDays: 10,
      isAutoPay: true,
      isUrgent: false,
      category: "Utilities",
      icon: "bill",
      color: "var(--cat-6)",
    },
    {
      id: "bill-3",
      name: "Credit card · Chase",
      amountInCents: 24500,
      dueDate: "May 8",
      dueInDays: 15,
      isAutoPay: false,
      isUrgent: false,
      category: "Card payment",
      icon: "card",
      color: "var(--cat-4)",
    },
    {
      id: "bill-4",
      name: "Gym",
      amountInCents: 2900,
      dueDate: "May 12",
      dueInDays: 19,
      isAutoPay: true,
      isUrgent: false,
      category: "Fitness",
      icon: "spark",
      color: "var(--cat-2)",
    },
    {
      id: "bill-5",
      name: "Phone · T-Mobile",
      amountInCents: 7500,
      dueDate: "May 15",
      dueInDays: 22,
      isAutoPay: true,
      isUrgent: false,
      category: "Utilities",
      icon: "bill",
      color: "var(--cat-6)",
    },
    {
      id: "bill-6",
      name: "Electricity",
      amountInCents: 8400,
      dueDate: "May 18",
      dueInDays: 25,
      isAutoPay: false,
      isUrgent: false,
      category: "Utilities",
      icon: "bill",
      color: "var(--cat-3)",
    },
  ],
  subscriptions: [
    {
      id: "sub-1",
      name: "Spotify",
      amountMonthlyInCents: 1099,
      nextDate: "May 5",
      isUsed: true,
      icon: "music",
      color: "#1db954",
    },
    {
      id: "sub-2",
      name: "Netflix",
      amountMonthlyInCents: 1599,
      nextDate: "May 12",
      isUsed: true,
      icon: "play",
      color: "#c44545",
    },
    {
      id: "sub-3",
      name: "NYT",
      amountMonthlyInCents: 400,
      nextDate: "May 2",
      isUsed: true,
      icon: "list",
      color: "#1c1a16",
    },
    {
      id: "sub-4",
      name: "iCloud",
      amountMonthlyInCents: 299,
      nextDate: "May 14",
      isUsed: false,
      icon: "lock",
      color: "#5a8a96",
    },
    {
      id: "sub-5",
      name: "Figma",
      amountMonthlyInCents: 1500,
      nextDate: "May 22",
      isUsed: false,
      icon: "spark",
      color: "#a259ff",
    },
  ],
};

// ---------------------------------------------------------------------------
// Insights
// ---------------------------------------------------------------------------

export const MOCK_INSIGHTS: Insight[] = [
  {
    id: "ins-0",
    glyph: "sparkle",
    tag: "Big news",
    tone: "pos",
    title: "You're saving 23% of income — up 5 points from March",
    body: "If you keep this rate, you'll hit your $5,000 emergency fund 2 months early.",
    cta: "See breakdown",
    isPinned: true,
    sparklineData: [12, 14, 15, 16, 17, 18, 20, 22, 23],
  },
  {
    id: "ins-1",
    glyph: "trend",
    tag: "Spotted",
    tone: "pos",
    title: "Coffee spend down 24%",
    body: "You spent $38 less on coffee than your 3-month average. Want to move it to a goal?",
    cta: "Move $38 to Lisbon",
    isPinned: false,
  },
  {
    id: "ins-2",
    glyph: "bill",
    tag: "Heads up",
    tone: "warn",
    title: "Dining hits limit in 4 days",
    body: "At current pace, you'll hit your $200 dining budget on Apr 27 — 3 days early.",
    cta: "See breakdown",
    isPinned: false,
  },
  {
    id: "ins-3",
    glyph: "cal",
    tag: "Habit",
    tone: "neutral",
    title: "Friday is your spendiest day",
    body: "You spend 2.3x more on Fridays than weekdays — mostly dining out.",
    cta: "See pattern",
    isPinned: false,
  },
  {
    id: "ins-4",
    glyph: "card",
    tag: "Found",
    tone: "warn",
    title: "3 forgotten subscriptions",
    body: "Figma, NYT, and iCloud haven't been opened in 30+ days. $22.99/mo total.",
    cta: "Review",
    isPinned: false,
  },
  {
    id: "ins-5",
    glyph: "goal",
    tag: "Win",
    tone: "pos",
    title: "Streak — 12 days under budget",
    body: "You've stayed under your daily allowance for 12 days straight. Keep it up.",
    cta: "See streak",
    isPinned: false,
  },
  {
    id: "ins-6",
    glyph: "pie",
    tag: "Compare",
    tone: "neutral",
    title: "You vs peers (25-34)",
    body: "You spend less on dining (-30%) but more on subscriptions (+18%) than peers.",
    cta: "Full comparison",
    isPinned: false,
  },
];

// ---------------------------------------------------------------------------
// Account detail
// ---------------------------------------------------------------------------

export const MOCK_ACCOUNT_DETAILS: Record<string, AccountDetail> = {
  chase: {
    account: MOCK_ACCOUNTS[0],
    recentTransactions: MOCK_TRANSACTIONS.slice(0, 6),
    monthlySummary: {
      moneyInInCents: 218000,
      moneyOutInCents: 124700,
      feesInCents: 0,
      interestInCents: 0,
    },
  },
  ally: {
    account: MOCK_ACCOUNTS[1],
    recentTransactions: MOCK_TRANSACTIONS.slice(0, 6),
    monthlySummary: {
      moneyInInCents: 218000,
      moneyOutInCents: 124700,
      feesInCents: 0,
      interestInCents: 412,
    },
  },
  broker: {
    account: MOCK_ACCOUNTS[2],
    recentTransactions: MOCK_TRANSACTIONS.slice(0, 6),
    monthlySummary: {
      moneyInInCents: 24000,
      moneyOutInCents: 0,
      feesInCents: 0,
      interestInCents: 0,
    },
  },
};

// ---------------------------------------------------------------------------
// Transactions summary
// ---------------------------------------------------------------------------

export const MOCK_TX_SUMMARY: TransactionsSummary = {
  moneyInInCents: 218412,
  moneyOutInCents: 124700,
  netInCents: 93712,
  dailyAvgOutInCents: 4100,
};
